/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as unauthorizedLayoutRouteImport } from './routes/(unauthorized)/layout'
import { Route as authorizedLayoutRouteImport } from './routes/(authorized)/layout'
import { Route as authorizedorganizationLayoutRouteImport } from './routes/(authorized)/(organization)/layout'
import { Route as unauthorizedSignupPageRouteImport } from './routes/(unauthorized)/signup/page'
import { Route as unauthorizedSigninPageRouteImport } from './routes/(unauthorized)/signin/page'
import { Route as unauthorizedSetNewPasswordPageRouteImport } from './routes/(unauthorized)/set-new-password/page'
import { Route as unauthorizedResetPasswordPageRouteImport } from './routes/(unauthorized)/reset-password/page'
import { Route as authorizedSelectOrganizationPageRouteImport } from './routes/(authorized)/select-organization/page'
import { Route as authorizedCreateOrganizationPageRouteImport } from './routes/(authorized)/create-organization/page'
import { Route as authorizedorganizationsidebarLayoutRouteImport } from './routes/(authorized)/(organization)/(sidebar)/layout'
import { Route as authorizedorganizationsidebarPageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/page'
import { Route as authorizedorganizationsidebarTasksPageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/tasks/page'
import { Route as authorizedorganizationsidebarSplatPageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/$/page'
import { Route as authorizedorganizationsidebarSettingsOrganizationPageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/settings/organization/page'
import { Route as authorizedorganizationsidebarSettingsAccountPageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/settings/account/page'

const unauthorizedLayoutRoute = unauthorizedLayoutRouteImport.update({
  id: '/(unauthorized)',
  getParentRoute: () => rootRouteImport,
} as any)
const authorizedLayoutRoute = authorizedLayoutRouteImport.update({
  id: '/(authorized)',
  getParentRoute: () => rootRouteImport,
} as any)
const authorizedorganizationLayoutRoute =
  authorizedorganizationLayoutRouteImport.update({
    id: '/(organization)',
    getParentRoute: () => authorizedLayoutRoute,
  } as any)
const unauthorizedSignupPageRoute = unauthorizedSignupPageRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => unauthorizedLayoutRoute,
} as any)
const unauthorizedSigninPageRoute = unauthorizedSigninPageRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => unauthorizedLayoutRoute,
} as any)
const unauthorizedSetNewPasswordPageRoute =
  unauthorizedSetNewPasswordPageRouteImport.update({
    id: '/set-new-password/',
    path: '/set-new-password/',
    getParentRoute: () => unauthorizedLayoutRoute,
  } as any)
const unauthorizedResetPasswordPageRoute =
  unauthorizedResetPasswordPageRouteImport.update({
    id: '/reset-password/',
    path: '/reset-password/',
    getParentRoute: () => unauthorizedLayoutRoute,
  } as any)
const authorizedSelectOrganizationPageRoute =
  authorizedSelectOrganizationPageRouteImport.update({
    id: '/select-organization/',
    path: '/select-organization/',
    getParentRoute: () => authorizedLayoutRoute,
  } as any)
const authorizedCreateOrganizationPageRoute =
  authorizedCreateOrganizationPageRouteImport.update({
    id: '/create-organization/',
    path: '/create-organization/',
    getParentRoute: () => authorizedLayoutRoute,
  } as any)
const authorizedorganizationsidebarLayoutRoute =
  authorizedorganizationsidebarLayoutRouteImport.update({
    id: '/(sidebar)',
    getParentRoute: () => authorizedorganizationLayoutRoute,
  } as any)
const authorizedorganizationsidebarPageRoute =
  authorizedorganizationsidebarPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authorizedorganizationsidebarLayoutRoute,
  } as any)
const authorizedorganizationsidebarTasksPageRoute =
  authorizedorganizationsidebarTasksPageRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => authorizedorganizationsidebarLayoutRoute,
  } as any)
const authorizedorganizationsidebarSplatPageRoute =
  authorizedorganizationsidebarSplatPageRouteImport.update({
    id: '/$/',
    path: '/$/',
    getParentRoute: () => authorizedorganizationsidebarLayoutRoute,
  } as any)
const authorizedorganizationsidebarSettingsOrganizationPageRoute =
  authorizedorganizationsidebarSettingsOrganizationPageRouteImport.update({
    id: '/settings/organization/',
    path: '/settings/organization/',
    getParentRoute: () => authorizedorganizationsidebarLayoutRoute,
  } as any)
const authorizedorganizationsidebarSettingsAccountPageRoute =
  authorizedorganizationsidebarSettingsAccountPageRouteImport.update({
    id: '/settings/account/',
    path: '/settings/account/',
    getParentRoute: () => authorizedorganizationsidebarLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/create-organization/': typeof authorizedCreateOrganizationPageRoute
  '/select-organization/': typeof authorizedSelectOrganizationPageRoute
  '/reset-password/': typeof unauthorizedResetPasswordPageRoute
  '/set-new-password/': typeof unauthorizedSetNewPasswordPageRoute
  '/signin/': typeof unauthorizedSigninPageRoute
  '/signup/': typeof unauthorizedSignupPageRoute
  '/': typeof authorizedorganizationsidebarPageRoute
  '/$/': typeof authorizedorganizationsidebarSplatPageRoute
  '/tasks/': typeof authorizedorganizationsidebarTasksPageRoute
  '/settings/account/': typeof authorizedorganizationsidebarSettingsAccountPageRoute
  '/settings/organization/': typeof authorizedorganizationsidebarSettingsOrganizationPageRoute
}
export interface FileRoutesByTo {
  '/create-organization': typeof authorizedCreateOrganizationPageRoute
  '/select-organization': typeof authorizedSelectOrganizationPageRoute
  '/reset-password': typeof unauthorizedResetPasswordPageRoute
  '/set-new-password': typeof unauthorizedSetNewPasswordPageRoute
  '/signin': typeof unauthorizedSigninPageRoute
  '/signup': typeof unauthorizedSignupPageRoute
  '/': typeof authorizedorganizationsidebarPageRoute
  '/$': typeof authorizedorganizationsidebarSplatPageRoute
  '/tasks': typeof authorizedorganizationsidebarTasksPageRoute
  '/settings/account': typeof authorizedorganizationsidebarSettingsAccountPageRoute
  '/settings/organization': typeof authorizedorganizationsidebarSettingsOrganizationPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authorized)': typeof authorizedLayoutRouteWithChildren
  '/(unauthorized)': typeof unauthorizedLayoutRouteWithChildren
  '/(authorized)/(organization)': typeof authorizedorganizationLayoutRouteWithChildren
  '/(authorized)/(organization)/(sidebar)': typeof authorizedorganizationsidebarLayoutRouteWithChildren
  '/(authorized)/create-organization/': typeof authorizedCreateOrganizationPageRoute
  '/(authorized)/select-organization/': typeof authorizedSelectOrganizationPageRoute
  '/(unauthorized)/reset-password/': typeof unauthorizedResetPasswordPageRoute
  '/(unauthorized)/set-new-password/': typeof unauthorizedSetNewPasswordPageRoute
  '/(unauthorized)/signin/': typeof unauthorizedSigninPageRoute
  '/(unauthorized)/signup/': typeof unauthorizedSignupPageRoute
  '/(authorized)/(organization)/(sidebar)/': typeof authorizedorganizationsidebarPageRoute
  '/(authorized)/(organization)/(sidebar)/$/': typeof authorizedorganizationsidebarSplatPageRoute
  '/(authorized)/(organization)/(sidebar)/tasks/': typeof authorizedorganizationsidebarTasksPageRoute
  '/(authorized)/(organization)/(sidebar)/settings/account/': typeof authorizedorganizationsidebarSettingsAccountPageRoute
  '/(authorized)/(organization)/(sidebar)/settings/organization/': typeof authorizedorganizationsidebarSettingsOrganizationPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/create-organization/'
    | '/select-organization/'
    | '/reset-password/'
    | '/set-new-password/'
    | '/signin/'
    | '/signup/'
    | '/'
    | '/$/'
    | '/tasks/'
    | '/settings/account/'
    | '/settings/organization/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/create-organization'
    | '/select-organization'
    | '/reset-password'
    | '/set-new-password'
    | '/signin'
    | '/signup'
    | '/'
    | '/$'
    | '/tasks'
    | '/settings/account'
    | '/settings/organization'
  id:
    | '__root__'
    | '/(authorized)'
    | '/(unauthorized)'
    | '/(authorized)/(organization)'
    | '/(authorized)/(organization)/(sidebar)'
    | '/(authorized)/create-organization/'
    | '/(authorized)/select-organization/'
    | '/(unauthorized)/reset-password/'
    | '/(unauthorized)/set-new-password/'
    | '/(unauthorized)/signin/'
    | '/(unauthorized)/signup/'
    | '/(authorized)/(organization)/(sidebar)/'
    | '/(authorized)/(organization)/(sidebar)/$/'
    | '/(authorized)/(organization)/(sidebar)/tasks/'
    | '/(authorized)/(organization)/(sidebar)/settings/account/'
    | '/(authorized)/(organization)/(sidebar)/settings/organization/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authorizedLayoutRoute: typeof authorizedLayoutRouteWithChildren
  unauthorizedLayoutRoute: typeof unauthorizedLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(unauthorized)': {
      id: '/(unauthorized)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof unauthorizedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authorized)': {
      id: '/(authorized)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authorizedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authorized)/(organization)': {
      id: '/(authorized)/(organization)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authorizedorganizationLayoutRouteImport
      parentRoute: typeof authorizedLayoutRoute
    }
    '/(unauthorized)/signup/': {
      id: '/(unauthorized)/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof unauthorizedSignupPageRouteImport
      parentRoute: typeof unauthorizedLayoutRoute
    }
    '/(unauthorized)/signin/': {
      id: '/(unauthorized)/signin/'
      path: '/signin'
      fullPath: '/signin/'
      preLoaderRoute: typeof unauthorizedSigninPageRouteImport
      parentRoute: typeof unauthorizedLayoutRoute
    }
    '/(unauthorized)/set-new-password/': {
      id: '/(unauthorized)/set-new-password/'
      path: '/set-new-password'
      fullPath: '/set-new-password/'
      preLoaderRoute: typeof unauthorizedSetNewPasswordPageRouteImport
      parentRoute: typeof unauthorizedLayoutRoute
    }
    '/(unauthorized)/reset-password/': {
      id: '/(unauthorized)/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof unauthorizedResetPasswordPageRouteImport
      parentRoute: typeof unauthorizedLayoutRoute
    }
    '/(authorized)/select-organization/': {
      id: '/(authorized)/select-organization/'
      path: '/select-organization'
      fullPath: '/select-organization/'
      preLoaderRoute: typeof authorizedSelectOrganizationPageRouteImport
      parentRoute: typeof authorizedLayoutRoute
    }
    '/(authorized)/create-organization/': {
      id: '/(authorized)/create-organization/'
      path: '/create-organization'
      fullPath: '/create-organization/'
      preLoaderRoute: typeof authorizedCreateOrganizationPageRouteImport
      parentRoute: typeof authorizedLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)': {
      id: '/(authorized)/(organization)/(sidebar)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authorizedorganizationsidebarLayoutRouteImport
      parentRoute: typeof authorizedorganizationLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/': {
      id: '/(authorized)/(organization)/(sidebar)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authorizedorganizationsidebarPageRouteImport
      parentRoute: typeof authorizedorganizationsidebarLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/tasks/': {
      id: '/(authorized)/(organization)/(sidebar)/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof authorizedorganizationsidebarTasksPageRouteImport
      parentRoute: typeof authorizedorganizationsidebarLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/$/': {
      id: '/(authorized)/(organization)/(sidebar)/$/'
      path: '/$'
      fullPath: '/$/'
      preLoaderRoute: typeof authorizedorganizationsidebarSplatPageRouteImport
      parentRoute: typeof authorizedorganizationsidebarLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/settings/organization/': {
      id: '/(authorized)/(organization)/(sidebar)/settings/organization/'
      path: '/settings/organization'
      fullPath: '/settings/organization/'
      preLoaderRoute: typeof authorizedorganizationsidebarSettingsOrganizationPageRouteImport
      parentRoute: typeof authorizedorganizationsidebarLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/settings/account/': {
      id: '/(authorized)/(organization)/(sidebar)/settings/account/'
      path: '/settings/account'
      fullPath: '/settings/account/'
      preLoaderRoute: typeof authorizedorganizationsidebarSettingsAccountPageRouteImport
      parentRoute: typeof authorizedorganizationsidebarLayoutRoute
    }
  }
}

interface authorizedorganizationsidebarLayoutRouteChildren {
  authorizedorganizationsidebarPageRoute: typeof authorizedorganizationsidebarPageRoute
  authorizedorganizationsidebarSplatPageRoute: typeof authorizedorganizationsidebarSplatPageRoute
  authorizedorganizationsidebarTasksPageRoute: typeof authorizedorganizationsidebarTasksPageRoute
  authorizedorganizationsidebarSettingsAccountPageRoute: typeof authorizedorganizationsidebarSettingsAccountPageRoute
  authorizedorganizationsidebarSettingsOrganizationPageRoute: typeof authorizedorganizationsidebarSettingsOrganizationPageRoute
}

const authorizedorganizationsidebarLayoutRouteChildren: authorizedorganizationsidebarLayoutRouteChildren =
  {
    authorizedorganizationsidebarPageRoute:
      authorizedorganizationsidebarPageRoute,
    authorizedorganizationsidebarSplatPageRoute:
      authorizedorganizationsidebarSplatPageRoute,
    authorizedorganizationsidebarTasksPageRoute:
      authorizedorganizationsidebarTasksPageRoute,
    authorizedorganizationsidebarSettingsAccountPageRoute:
      authorizedorganizationsidebarSettingsAccountPageRoute,
    authorizedorganizationsidebarSettingsOrganizationPageRoute:
      authorizedorganizationsidebarSettingsOrganizationPageRoute,
  }

const authorizedorganizationsidebarLayoutRouteWithChildren =
  authorizedorganizationsidebarLayoutRoute._addFileChildren(
    authorizedorganizationsidebarLayoutRouteChildren,
  )

interface authorizedorganizationLayoutRouteChildren {
  authorizedorganizationsidebarLayoutRoute: typeof authorizedorganizationsidebarLayoutRouteWithChildren
}

const authorizedorganizationLayoutRouteChildren: authorizedorganizationLayoutRouteChildren =
  {
    authorizedorganizationsidebarLayoutRoute:
      authorizedorganizationsidebarLayoutRouteWithChildren,
  }

const authorizedorganizationLayoutRouteWithChildren =
  authorizedorganizationLayoutRoute._addFileChildren(
    authorizedorganizationLayoutRouteChildren,
  )

interface authorizedLayoutRouteChildren {
  authorizedorganizationLayoutRoute: typeof authorizedorganizationLayoutRouteWithChildren
  authorizedCreateOrganizationPageRoute: typeof authorizedCreateOrganizationPageRoute
  authorizedSelectOrganizationPageRoute: typeof authorizedSelectOrganizationPageRoute
}

const authorizedLayoutRouteChildren: authorizedLayoutRouteChildren = {
  authorizedorganizationLayoutRoute:
    authorizedorganizationLayoutRouteWithChildren,
  authorizedCreateOrganizationPageRoute: authorizedCreateOrganizationPageRoute,
  authorizedSelectOrganizationPageRoute: authorizedSelectOrganizationPageRoute,
}

const authorizedLayoutRouteWithChildren =
  authorizedLayoutRoute._addFileChildren(authorizedLayoutRouteChildren)

interface unauthorizedLayoutRouteChildren {
  unauthorizedResetPasswordPageRoute: typeof unauthorizedResetPasswordPageRoute
  unauthorizedSetNewPasswordPageRoute: typeof unauthorizedSetNewPasswordPageRoute
  unauthorizedSigninPageRoute: typeof unauthorizedSigninPageRoute
  unauthorizedSignupPageRoute: typeof unauthorizedSignupPageRoute
}

const unauthorizedLayoutRouteChildren: unauthorizedLayoutRouteChildren = {
  unauthorizedResetPasswordPageRoute: unauthorizedResetPasswordPageRoute,
  unauthorizedSetNewPasswordPageRoute: unauthorizedSetNewPasswordPageRoute,
  unauthorizedSigninPageRoute: unauthorizedSigninPageRoute,
  unauthorizedSignupPageRoute: unauthorizedSignupPageRoute,
}

const unauthorizedLayoutRouteWithChildren =
  unauthorizedLayoutRoute._addFileChildren(unauthorizedLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authorizedLayoutRoute: authorizedLayoutRouteWithChildren,
  unauthorizedLayoutRoute: unauthorizedLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
