/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as unauthorizedLayoutRouteImport } from './routes/(unauthorized)/layout'
import { Route as authorizedLayoutRouteImport } from './routes/(authorized)/layout'
import { Route as authorizedsidebarLayoutRouteImport } from './routes/(authorized)/(sidebar)/layout'
import { Route as unauthorizedSignupPageRouteImport } from './routes/(unauthorized)/signup/page'
import { Route as unauthorizedSigninPageRouteImport } from './routes/(unauthorized)/signin/page'
import { Route as unauthorizedSetNewPasswordPageRouteImport } from './routes/(unauthorized)/set-new-password/page'
import { Route as unauthorizedResetPasswordPageRouteImport } from './routes/(unauthorized)/reset-password/page'
import { Route as authorizedCreateOrganizationPageRouteImport } from './routes/(authorized)/create-organization/page'
import { Route as authorizedsidebarPageRouteImport } from './routes/(authorized)/(sidebar)/page'
import { Route as authorizedsidebarTasksPageRouteImport } from './routes/(authorized)/(sidebar)/tasks/page'
import { Route as authorizedsidebarSplatPageRouteImport } from './routes/(authorized)/(sidebar)/$/page'
import { Route as authorizedsidebarSettingsOrganizationPageRouteImport } from './routes/(authorized)/(sidebar)/settings/organization/page'
import { Route as authorizedsidebarSettingsAccountPageRouteImport } from './routes/(authorized)/(sidebar)/settings/account/page'

const unauthorizedLayoutRoute = unauthorizedLayoutRouteImport.update({
  id: '/(unauthorized)',
  getParentRoute: () => rootRouteImport,
} as any)
const authorizedLayoutRoute = authorizedLayoutRouteImport.update({
  id: '/(authorized)',
  getParentRoute: () => rootRouteImport,
} as any)
const authorizedsidebarLayoutRoute = authorizedsidebarLayoutRouteImport.update({
  id: '/(sidebar)',
  getParentRoute: () => authorizedLayoutRoute,
} as any)
const unauthorizedSignupPageRoute = unauthorizedSignupPageRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => unauthorizedLayoutRoute,
} as any)
const unauthorizedSigninPageRoute = unauthorizedSigninPageRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => unauthorizedLayoutRoute,
} as any)
const unauthorizedSetNewPasswordPageRoute =
  unauthorizedSetNewPasswordPageRouteImport.update({
    id: '/set-new-password/',
    path: '/set-new-password/',
    getParentRoute: () => unauthorizedLayoutRoute,
  } as any)
const unauthorizedResetPasswordPageRoute =
  unauthorizedResetPasswordPageRouteImport.update({
    id: '/reset-password/',
    path: '/reset-password/',
    getParentRoute: () => unauthorizedLayoutRoute,
  } as any)
const authorizedCreateOrganizationPageRoute =
  authorizedCreateOrganizationPageRouteImport.update({
    id: '/create-organization/',
    path: '/create-organization/',
    getParentRoute: () => authorizedLayoutRoute,
  } as any)
const authorizedsidebarPageRoute = authorizedsidebarPageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authorizedsidebarLayoutRoute,
} as any)
const authorizedsidebarTasksPageRoute =
  authorizedsidebarTasksPageRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => authorizedsidebarLayoutRoute,
  } as any)
const authorizedsidebarSplatPageRoute =
  authorizedsidebarSplatPageRouteImport.update({
    id: '/$/',
    path: '/$/',
    getParentRoute: () => authorizedsidebarLayoutRoute,
  } as any)
const authorizedsidebarSettingsOrganizationPageRoute =
  authorizedsidebarSettingsOrganizationPageRouteImport.update({
    id: '/settings/organization/',
    path: '/settings/organization/',
    getParentRoute: () => authorizedsidebarLayoutRoute,
  } as any)
const authorizedsidebarSettingsAccountPageRoute =
  authorizedsidebarSettingsAccountPageRouteImport.update({
    id: '/settings/account/',
    path: '/settings/account/',
    getParentRoute: () => authorizedsidebarLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof authorizedsidebarPageRoute
  '/create-organization/': typeof authorizedCreateOrganizationPageRoute
  '/reset-password/': typeof unauthorizedResetPasswordPageRoute
  '/set-new-password/': typeof unauthorizedSetNewPasswordPageRoute
  '/signin/': typeof unauthorizedSigninPageRoute
  '/signup/': typeof unauthorizedSignupPageRoute
  '/$/': typeof authorizedsidebarSplatPageRoute
  '/tasks/': typeof authorizedsidebarTasksPageRoute
  '/settings/account/': typeof authorizedsidebarSettingsAccountPageRoute
  '/settings/organization/': typeof authorizedsidebarSettingsOrganizationPageRoute
}
export interface FileRoutesByTo {
  '/': typeof authorizedsidebarPageRoute
  '/create-organization': typeof authorizedCreateOrganizationPageRoute
  '/reset-password': typeof unauthorizedResetPasswordPageRoute
  '/set-new-password': typeof unauthorizedSetNewPasswordPageRoute
  '/signin': typeof unauthorizedSigninPageRoute
  '/signup': typeof unauthorizedSignupPageRoute
  '/$': typeof authorizedsidebarSplatPageRoute
  '/tasks': typeof authorizedsidebarTasksPageRoute
  '/settings/account': typeof authorizedsidebarSettingsAccountPageRoute
  '/settings/organization': typeof authorizedsidebarSettingsOrganizationPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authorized)': typeof authorizedLayoutRouteWithChildren
  '/(unauthorized)': typeof unauthorizedLayoutRouteWithChildren
  '/(authorized)/(sidebar)': typeof authorizedsidebarLayoutRouteWithChildren
  '/(authorized)/(sidebar)/': typeof authorizedsidebarPageRoute
  '/(authorized)/create-organization/': typeof authorizedCreateOrganizationPageRoute
  '/(unauthorized)/reset-password/': typeof unauthorizedResetPasswordPageRoute
  '/(unauthorized)/set-new-password/': typeof unauthorizedSetNewPasswordPageRoute
  '/(unauthorized)/signin/': typeof unauthorizedSigninPageRoute
  '/(unauthorized)/signup/': typeof unauthorizedSignupPageRoute
  '/(authorized)/(sidebar)/$/': typeof authorizedsidebarSplatPageRoute
  '/(authorized)/(sidebar)/tasks/': typeof authorizedsidebarTasksPageRoute
  '/(authorized)/(sidebar)/settings/account/': typeof authorizedsidebarSettingsAccountPageRoute
  '/(authorized)/(sidebar)/settings/organization/': typeof authorizedsidebarSettingsOrganizationPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-organization/'
    | '/reset-password/'
    | '/set-new-password/'
    | '/signin/'
    | '/signup/'
    | '/$/'
    | '/tasks/'
    | '/settings/account/'
    | '/settings/organization/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-organization'
    | '/reset-password'
    | '/set-new-password'
    | '/signin'
    | '/signup'
    | '/$'
    | '/tasks'
    | '/settings/account'
    | '/settings/organization'
  id:
    | '__root__'
    | '/(authorized)'
    | '/(unauthorized)'
    | '/(authorized)/(sidebar)'
    | '/(authorized)/(sidebar)/'
    | '/(authorized)/create-organization/'
    | '/(unauthorized)/reset-password/'
    | '/(unauthorized)/set-new-password/'
    | '/(unauthorized)/signin/'
    | '/(unauthorized)/signup/'
    | '/(authorized)/(sidebar)/$/'
    | '/(authorized)/(sidebar)/tasks/'
    | '/(authorized)/(sidebar)/settings/account/'
    | '/(authorized)/(sidebar)/settings/organization/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authorizedLayoutRoute: typeof authorizedLayoutRouteWithChildren
  unauthorizedLayoutRoute: typeof unauthorizedLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(unauthorized)': {
      id: '/(unauthorized)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof unauthorizedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authorized)': {
      id: '/(authorized)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authorizedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authorized)/(sidebar)': {
      id: '/(authorized)/(sidebar)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authorizedsidebarLayoutRouteImport
      parentRoute: typeof authorizedLayoutRoute
    }
    '/(unauthorized)/signup/': {
      id: '/(unauthorized)/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof unauthorizedSignupPageRouteImport
      parentRoute: typeof unauthorizedLayoutRoute
    }
    '/(unauthorized)/signin/': {
      id: '/(unauthorized)/signin/'
      path: '/signin'
      fullPath: '/signin/'
      preLoaderRoute: typeof unauthorizedSigninPageRouteImport
      parentRoute: typeof unauthorizedLayoutRoute
    }
    '/(unauthorized)/set-new-password/': {
      id: '/(unauthorized)/set-new-password/'
      path: '/set-new-password'
      fullPath: '/set-new-password/'
      preLoaderRoute: typeof unauthorizedSetNewPasswordPageRouteImport
      parentRoute: typeof unauthorizedLayoutRoute
    }
    '/(unauthorized)/reset-password/': {
      id: '/(unauthorized)/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof unauthorizedResetPasswordPageRouteImport
      parentRoute: typeof unauthorizedLayoutRoute
    }
    '/(authorized)/create-organization/': {
      id: '/(authorized)/create-organization/'
      path: '/create-organization'
      fullPath: '/create-organization/'
      preLoaderRoute: typeof authorizedCreateOrganizationPageRouteImport
      parentRoute: typeof authorizedLayoutRoute
    }
    '/(authorized)/(sidebar)/': {
      id: '/(authorized)/(sidebar)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authorizedsidebarPageRouteImport
      parentRoute: typeof authorizedsidebarLayoutRoute
    }
    '/(authorized)/(sidebar)/tasks/': {
      id: '/(authorized)/(sidebar)/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof authorizedsidebarTasksPageRouteImport
      parentRoute: typeof authorizedsidebarLayoutRoute
    }
    '/(authorized)/(sidebar)/$/': {
      id: '/(authorized)/(sidebar)/$/'
      path: '/$'
      fullPath: '/$/'
      preLoaderRoute: typeof authorizedsidebarSplatPageRouteImport
      parentRoute: typeof authorizedsidebarLayoutRoute
    }
    '/(authorized)/(sidebar)/settings/organization/': {
      id: '/(authorized)/(sidebar)/settings/organization/'
      path: '/settings/organization'
      fullPath: '/settings/organization/'
      preLoaderRoute: typeof authorizedsidebarSettingsOrganizationPageRouteImport
      parentRoute: typeof authorizedsidebarLayoutRoute
    }
    '/(authorized)/(sidebar)/settings/account/': {
      id: '/(authorized)/(sidebar)/settings/account/'
      path: '/settings/account'
      fullPath: '/settings/account/'
      preLoaderRoute: typeof authorizedsidebarSettingsAccountPageRouteImport
      parentRoute: typeof authorizedsidebarLayoutRoute
    }
  }
}

interface authorizedsidebarLayoutRouteChildren {
  authorizedsidebarPageRoute: typeof authorizedsidebarPageRoute
  authorizedsidebarSplatPageRoute: typeof authorizedsidebarSplatPageRoute
  authorizedsidebarTasksPageRoute: typeof authorizedsidebarTasksPageRoute
  authorizedsidebarSettingsAccountPageRoute: typeof authorizedsidebarSettingsAccountPageRoute
  authorizedsidebarSettingsOrganizationPageRoute: typeof authorizedsidebarSettingsOrganizationPageRoute
}

const authorizedsidebarLayoutRouteChildren: authorizedsidebarLayoutRouteChildren =
  {
    authorizedsidebarPageRoute: authorizedsidebarPageRoute,
    authorizedsidebarSplatPageRoute: authorizedsidebarSplatPageRoute,
    authorizedsidebarTasksPageRoute: authorizedsidebarTasksPageRoute,
    authorizedsidebarSettingsAccountPageRoute:
      authorizedsidebarSettingsAccountPageRoute,
    authorizedsidebarSettingsOrganizationPageRoute:
      authorizedsidebarSettingsOrganizationPageRoute,
  }

const authorizedsidebarLayoutRouteWithChildren =
  authorizedsidebarLayoutRoute._addFileChildren(
    authorizedsidebarLayoutRouteChildren,
  )

interface authorizedLayoutRouteChildren {
  authorizedsidebarLayoutRoute: typeof authorizedsidebarLayoutRouteWithChildren
  authorizedCreateOrganizationPageRoute: typeof authorizedCreateOrganizationPageRoute
}

const authorizedLayoutRouteChildren: authorizedLayoutRouteChildren = {
  authorizedsidebarLayoutRoute: authorizedsidebarLayoutRouteWithChildren,
  authorizedCreateOrganizationPageRoute: authorizedCreateOrganizationPageRoute,
}

const authorizedLayoutRouteWithChildren =
  authorizedLayoutRoute._addFileChildren(authorizedLayoutRouteChildren)

interface unauthorizedLayoutRouteChildren {
  unauthorizedResetPasswordPageRoute: typeof unauthorizedResetPasswordPageRoute
  unauthorizedSetNewPasswordPageRoute: typeof unauthorizedSetNewPasswordPageRoute
  unauthorizedSigninPageRoute: typeof unauthorizedSigninPageRoute
  unauthorizedSignupPageRoute: typeof unauthorizedSignupPageRoute
}

const unauthorizedLayoutRouteChildren: unauthorizedLayoutRouteChildren = {
  unauthorizedResetPasswordPageRoute: unauthorizedResetPasswordPageRoute,
  unauthorizedSetNewPasswordPageRoute: unauthorizedSetNewPasswordPageRoute,
  unauthorizedSigninPageRoute: unauthorizedSigninPageRoute,
  unauthorizedSignupPageRoute: unauthorizedSignupPageRoute,
}

const unauthorizedLayoutRouteWithChildren =
  unauthorizedLayoutRoute._addFileChildren(unauthorizedLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authorizedLayoutRoute: authorizedLayoutRouteWithChildren,
  unauthorizedLayoutRoute: unauthorizedLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
